<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>6c22a4b8-5983-407b-acbc-45ca5f8d7e0f</elementGuidId>
    <imagePath></imagePath>
    <name>button_tax</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[1]/div[1]/form[1]/div[1]/div[2]/button[2]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>#tax</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@id,'tax') and equals(@class,'MuiButtonBase-root MuiButton-root MuiButton-text MuiButton-textPrimary MuiButton-sizeMedium MuiButton-textSizeMedium MuiButton-root MuiButton-text MuiButton-textPrimary MuiButton-sizeMedium MuiButton-textSizeMedium css-1ommr5q')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>False</useRalativeImagePath>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>class</name>
        <type>Main</type>
        <value>MuiButtonBase-root MuiButton-root MuiButton-text MuiButton-textPrimary MuiButton-sizeMedium MuiButton-textSizeMedium MuiButton-root MuiButton-text MuiButton-textPrimary MuiButton-sizeMedium MuiButton-textSizeMedium css-1ommr5q</value>
        <webElementGuid>af3bfb59-18e4-4343-bc86-e18856005825</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>id</name>
        <type>Main</type>
        <value>tax</value>
        <webElementGuid>cfa61c1b-a5c5-47e6-a189-c3fd4f1cc592</webElementGuid>
    </webElementProperties>
</WebElementEntity>