<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>c667003d-1db0-4373-a7fa-7c3efce381b3</elementGuidId>
    <imagePath></imagePath>
    <name>button_personal_next</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[1]/div[1]/form[1]/div[1]/button[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>#member-next</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@id,'member-next') and equals(@class,'MuiButtonBase-root MuiButton-root MuiButton-text MuiButton-textPrimary MuiButton-sizeMedium MuiButton-textSizeMedium MuiButton-root MuiButton-text MuiButton-textPrimary MuiButton-sizeMedium MuiButton-textSizeMedium css-1ommr5q')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>False</useRalativeImagePath>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>class</name>
        <type>Main</type>
        <value>MuiButtonBase-root MuiButton-root MuiButton-text MuiButton-textPrimary MuiButton-sizeMedium MuiButton-textSizeMedium MuiButton-root MuiButton-text MuiButton-textPrimary MuiButton-sizeMedium MuiButton-textSizeMedium css-1ommr5q</value>
        <webElementGuid>12a5b7ae-0ee7-49a8-bee2-03ad97db5913</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>id</name>
        <type>Main</type>
        <value>member-next</value>
        <webElementGuid>bbb3c64f-3a64-493c-baa8-dabef84fd019</webElementGuid>
    </webElementProperties>
</WebElementEntity>