<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>2ce6f07d-b03f-4a99-88c2-9452766ac8b2</elementGuidId>
    <imagePath></imagePath>
    <name>input_object_7</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>('//body/div[1]/div[1]/div[1]/form[1]/div[1]/div[3]/div[2]/label[1]/span[1]/input[1]',)</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>form</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>False</useRalativeImagePath>
</WebElementEntity>